name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9.9-eclipse-temurin-21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test with Maven
        run: mvn clean test package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: ./target/*.jar
